const t = {
  ADA: {
    'coin/token': 'ADA',
    percentage_to_sell_at: '',
    'purchase id': '9',
    'total cost': '800',
    unit: '1000',
  },
  BTC: {
    'coin/token': 'BTC',
    percentage_to_sell_at: '50',
    'purchase id': '7',
    'total cost': '13000',
    unit: '1',
  },
  DOT: {
    'coin/token': 'DOT',
    percentage_to_sell_at: '80',
    'purchase id': '8',
    'total cost': '400',
    unit: '4',
  },
  ETH: {
    'coin/token': 'ETH',
    percentage_to_sell_at: '25',
    'purchase id': '1',
    'total cost': '780',
    unit: '0.270.5',
  },
  GAS: {
    'coin/token': 'GAS',
    percentage_to_sell_at: '',
    'purchase id': '2',
    'total cost': '455',
    unit: '3010',
  },
  OXT: {
    'coin/token': 'OXT',
    percentage_to_sell_at: '',
    'purchase id': '5',
    'total cost': '1200',
    unit: '1000',
  },
  VET: {
    'coin/token': 'VET',
    percentage_to_sell_at: '',
    'purchase id': '3',
    'total cost': '45',
    unit: '500',
  },
};
